// @flow
const TODOS = Object.freeze({
  CLEAR_COMPLETED: 'TODOS/CLEAR_COMPLETED',
  CREATE_TODO: 'TODOS/CREATE_TODO',
  REMOVE_TODO: 'TODOS/REMOVE_TODO',
  SAVE_TODO: 'TODOS/SAVE_TODO',
  TOGGLE_TODO: 'TODOS/TOGGLE_TODO',
  TOGGLE_COMPLETE: 'TODOS/TOGGLE_COMPLETE',
  TOGGLE_ITEM_COMPLETE: 'TODOS/TOGGLE_TODO_COMPLETE'
})

export default TODOS
